#! /usr/bin/env ruby
# frozen_string_literal: true

require 'toml'

contest_name = ARGV.first

`cargo atcoder new #{contest_name}`

file = [contest_name, 'Cargo.toml'].join('/')
s = File.write(file, <<-EOS)

[package]
name = "#{contest_name}"
version = "0.1.0"
authors = ["hkdnet <satoko.itse@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
comp = { git = "https://github.com/hkdnet/comp-rs" }

proconio = "*"
num-bigint = "0.2.6"
num-traits = "0.2.11"
num-integer = "0.1.42"

[profile.release]
lto = true
panic = 'abort'
EOS

Dir[[contest_name, 'src', 'bin', '*.rs'].join('/')].each do |file|
  s = File.read(file)
  s = <<-EOS + s
#![allow(unused_imports)]
use proconio::input;
use proconio::marker::*;
EOS
  File.write(file, s)
end

