[package]
name = "abc152"
version = "0.1.0"
authors = ["hkdnet <satoko.itse@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
