[package]
name = "abc317"
version = "0.1.0"
authors = ["GitHub <noreply@github.com>"]
edition = "2018"

proconio = "*"
num-bigint = "0.4.3"
num-traits = "0.2.11"
num-integer = "0.1.42"

[profile.release]
lto = true
panic = 'abort'
